
#config.yaml

gpt-key: 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

jpm-core-loc: C:\\Users\\PC\\Desktop\\Python\\jpm-nlp\\jpm_core\\jpm.jar

gpt-version: gpt-4.1